name: big_brother
description: All your data are belong to us
version: 0.0.1
author: will.haslett@gmail.com
homepage: twitter.com/willhaslett

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  camera: ^0.5.7+2
  sensors: ^0.4.1+5
  flutter_sound: ^1.7.0
  location: ^2.3.5
  google_maps_flutter: ^0.5.21+15
  light: ^0.1.1
  all_sensors: ^0.1.1
  screen_state: ^0.1.1
  cloud_firestore: ^0.13.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
